### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by spawnax** [hawkxtreme/UnloadingRelease1C#1]
{Модуль C:\Program Files\OneScript\lib\fluent\src\Классы\ПроцессорКоллекций.os / Ошибка в строке: 966 / Внешнее исключение (ScriptEngine.Compiler.CompilerException): {Модуль <string 0B4EDC33> / Ошибка в строке: 11,9 / Неизвестная операция}
        Первый, Второй -> СтроковыеФункции.СравнитьВерсии(Первый.НомерВерсии,  Второй.НомерВерсии) < 0}

**Comment by hawkxtreme** [comment]
нужен пример файла настроек для воспроизведения проблемы.
также прошу сначала обновить библиотеки v8runner, v8storage

**Comment by spawnax** [comment]
Спасибо, но отбой, стояла старая версия библиотеки fluent
